### ISSUE TITLE
Summary of bat call detections

### ISSUE THREAD

**Issue by leewujung** [uw-echospace/ubna-field#10]
The goal of this analysis is to get a rough sense of when bats emitting calls in different frequency bands show up in terms of time of day. The detections will come from RavenPro energy detectors. Once we have the dataframes (and corresponding CSV files) we can do more follow-up analysis on environmental conditions etc.

For the first shot let's do this summary until all data collected until July 12 recovery.

### Tasks
- [ ] batch detection of bat calls
- [ ] generate a notebook that loop through all detection files to build a pandas dataframe
   - dataframe has the following columns: filename, date, start time (UTC), end time (UTC), number of LF calls, number of HF calls, notes if any
   - date/start time/end time can be parsed from filename: check out [`dateutils`](https://dateutil.readthedocs.io/en/stable/index.html); if that doesn't work, use `re` and construct `datetime.datetime` object manually
- [ ] plot histograms of number of call detections, one for each day, with bars of two colors (LF and HF calls)
- [ ] plot histogram of number of call detections with data from _all_ days pooled together
