### ISSUE TITLE
Create protocol for detecting bat calls in RavenPro

### ISSUE THREAD

**Issue by leewujung** [uw-echospace/ubna-field#21]
We now have protocols for deployment and recovery (mainly #12), and the detection summary notebook is on the way (#20).

Now we need a protocol to fill in the gap between these -- the steps that are used to do automatic detection of bat calls using RavenPro.

### Tasks
Not sure about the steps but the items I can think of to be included are:
- [ ] detection settings for the HF and LF calls
- [ ] output folder naming convention
- [ ] link to RavenPro docs or sections for some details of how to apply the detection in batch mode
- [ ] seems a good idea to add a few extra columns to the deployment file?
   - "call detected?": Y or N -- whether or not detection have been performed on these files
   - "detection result folder" -- self-explanatory
   - "detector" -- haha this is a bad name, I am trying to find a succinct column name for the person who runs the detections
- [ ] also to follow what's included in #20, it seems a good idea to upload the detection outputs to this repo, we can have 2 folders:
   - `detection_raw`: folder where the outputs from RavenPro are stored
   - `detection_checked`: folder where the outputs manually checked/corrected from the raw detection outputs are stored

@aditya-uw : see what you think! Let's go back and forth in the PR. Thanks!
